
app = "glideforce"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  image = "akorkh/glideforce:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  StripeSettings__PublishableKey = "pk_test_51OHmt7FTVL1n528tkads1KBWc24mSqFUCIGNmKjDxUx9I5MCDJPC3hJl3IIQ7KHiXTeFQMWnnvwcm3ZRscHW7zbw00wypzxrUa"
  Cloudinary__CloudName = "dkedpawwh"
  Cloudinary__ApiKey = "573843963545761"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
